<?php

return [
    'meta' => [
        'title' => 'ReNUTS — Creating new value after pressing | FORCENTO',
        'description' => 'ReNUTS studies the food valorisation of press cakes from nuts and seeds through a scientific and regional approach.',
    ],
    'nav' => [
        'project' => 'The project',
        'science' => 'R&D',
        'chain' => 'Value chain',
        'status' => 'Progress',
        'partners' => 'Partners',
        'contact' => 'Let’s talk',
        'navigation' => 'Navigation',
        'menu' => 'Menu',
        'language' => 'Language',
    ],
    'hero' => [
        'eyebrow' => 'Food innovation · French-speaking Switzerland',
        'title' => 'Creating new value from what remains after pressing.',
        'text' => 'Every year, press cakes — the solid material left after walnuts, hazelnuts, almonds or seeds are pressed for oil — are produced locally and largely directed to animal feed. ReNUTS aims to determine scientifically what value this existing resource can have for human food.',
        'primary' => 'Discover the project',
        'secondary' => 'Build the value chain with us',
        'status' => 'Pre-industrial project · R&D being structured',
    ],
    'resource' => [
        'eyebrow' => 'The project',
        'title' => 'The resource already exists. Its value still has to be proven.',
        'text1' => 'The project is not about launching yet another protein bar. It starts by characterising an existing material, securing its food use and understanding how it can be transformed reproducibly.',
        'text2' => 'The next objective is to develop ingredients and applications suited to artisan or industrial production, without assuming nutritional performance before it has been measured.',
        'note' => 'Nutritional values, stability and functional properties must be established material by material, according to origin and pressing process.',
    ],
    'opportunity' => [
        'eyebrow' => 'Why now',
        'title' => 'Growing interest in protein — and a growing need for credibility.',
        'text' => 'Protein-rich products are multiplying, but their real value depends on composition and formulation. ReNUTS takes the opposite approach: start from a raw, local, existing material and prove its value before trying to sell it.',
    ],
    'process' => [
        'eyebrow' => 'From resource to market',
        'title' => 'Turning an existing material into new value.',
        'steps' => [
            ['Pressing', 'A regional material generated by an existing process.'],
            ['Press cake', 'The co-product becomes a resource to characterise.'],
            ['Analysis', 'Composition, safety, stability and functionality.'],
            ['R&D', 'Formulation, trials, processes and validation.'],
            ['Applications', 'Demonstrators, ingredients and new uses.'],
            ['New value', 'Reproducible and economically viable outlets.'],
        ],
    ],
    'science' => [
        'eyebrow' => 'R&D · Our scientific approach',
        'title' => 'Measure what each material can actually do.',
        'intro' => 'Before any commercial formulation, R&D must establish the composition, safety, stability and behaviour of each material.',
        'cards' => [
            ['Nutritional composition', 'Protein, fibre, residual fats, carbohydrates, minerals and energy value.'],
            ['Protein quality', 'Amino-acid profile and potential complementarity between materials.'],
            ['Food safety', 'Microbiology, allergens, cross-contamination, foreign bodies and traceability.'],
            ['Stability', 'Moisture, water activity, oxidation, storage and shelf life.'],
            ['Functional properties', 'Particle size, texture, absorption, formulation behaviour and the influence of residual oil.'],
            ['Regulatory framework', 'Claims and market conditions must be established from measured results.'],
        ],
        'note' => 'Oxidation, allergens, shelf life and reproducibility are not issues to address afterwards: they are part of the R&D programme from day one.',
    ],
    'demo' => [
        'eyebrow' => 'First demonstrator',
        'title' => 'A bar to learn from, not to limit the project.',
        'text' => 'A raw, no-bake food bar is used as the first technical demonstrator. It enables rapid testing of incorporation rate, texture, taste, binding, stability, storage and industrial feasibility.',
        'more' => 'Over time, the material could also be used in functional flours, granolas, muesli mixes, crackers, breakfast products or B2B ingredients.',
        'badge' => 'Proof of concept',
    ],
    'chain' => [
        'eyebrow' => 'The value chain',
        'title' => 'Connecting material, science, industry and market.',
        'intro' => 'ReNUTS starts in the canton of Vaud with the ambition to build a coherent value chain around a resource that is already available.',
        'actors' => [
            ['Mills & producers', 'Materials, volumes, origin, traceability, pressing processes and representative samples.'],
            ['Universities & applied sciences', 'Characterisation, nutrition, functional properties, formulation and stability.'],
            ['Laboratories', 'Nutritional, physicochemical and microbiological analyses.'],
            ['Food industry', 'Pilot trials, processes, reproducibility, packaging and scale-up.'],
            ['FORCENTO', 'Project leadership, product innovation, business model, commercial development and value-chain coordination.'],
        ],
    ],
    'local' => [
        'eyebrow' => 'Rooted in Vaud',
        'title' => 'Starting from an existing regional resource.',
        'text' => 'The canton of Vaud has active players in the cold pressing of nuts and oilseeds. ReNUTS aims to document the material, its volumes and characteristics, while also exploring formulations that make use of regional ingredients.',
        'note' => 'One avenue being explored is the use of binders made from local quince, apple or pear as alternatives to certain imported ingredients. This still requires technical validation, and ReNUTS does not currently claim a “100% Vaud” product.',
        'graphic' => 'LOCAL VALUE',
    ],
    'status' => [
        'eyebrow' => 'Progress',
        'title' => 'A pre-industrial project currently being structured.',
        'phases' => [
            [
                'label' => 'Phase 1 · In progress',
                'title' => 'Build the project foundations',
                'items' => [
                    'ReNUTS concept defined and R&D programme structured.',
                    'First material partner identified: positive discussions with Moulin de Sévery.',
                    'Initial formulation routes defined.',
                    'Contact initiated with SPEI to explore an NPR approach.',
                ],
            ],
            [
                'label' => 'Phase 2 · Next step',
                'title' => 'Measure, formulate and demonstrate',
                'items' => [
                    'Full laboratory characterisation of press cake: composition, safety and stability.',
                    'First demonstrator — a raw bar — formulated and tested.',
                    'Build the partner consortium.',
                ],
            ],
            [
                'label' => 'Phase 3 · Upcoming',
                'title' => 'Scale up',
                'items' => [
                    'Industrial pilot trials and scale-up.',
                    'Submit the NPR application.',
                    'First commercial partnerships and B2B outlets.',
                ],
            ],
        ],
    ],
    'partners' => [
        'eyebrow' => 'Join the project',
        'title' => 'Let’s build the value chain together.',
        'text' => 'ReNUTS is built with complementary partners. There are three concrete ways to contribute.',
        'cta' => 'Talk with us',
        'axes' => [
            [
                'kicker' => 'You have the material',
                'title' => 'Suppliers & producers',
                'text' => 'Mills, pressers and oilseed producers: contribute volumes, traceability, value-chain data and representative samples.',
                'cta' => 'Become a material partner',
            ],
            [
                'kicker' => 'You have the science or industry',
                'title' => 'Scientific & industrial partners',
                'text' => 'Universities, applied-science schools, laboratories and food manufacturers: contribute to characterisation, prototyping and scale-up.',
                'cta' => 'Join as an R&D partner',
            ],
            [
                'kicker' => 'You can help accelerate',
                'title' => 'Institutional & financial partners',
                'text' => 'Support the R&D phase and value-chain structuring, including the NPR approach currently being explored.',
                'cta' => 'Support the project',
            ],
        ],
    ],
    'about' => [
        'eyebrow' => 'FORCENTO · The team',
        'title' => 'Food innovation as a starting point.',
        'text' => 'ReNUTS is led by FORCENTO Sàrl. Kim and Florian bring their entrepreneurial experience in alternative proteins and food innovation to a simple approach: start with an existing regional resource, scientifically demonstrate its potential, then build an economically viable value chain around it.',
        'founders' => 'Co-founders',
    ],
    'faq' => [
        'eyebrow' => 'Frequently asked questions',
        'title' => 'The questions we hear most often.',
        'items' => [
            [
                'question' => 'Is ReNUTS just another protein bar?',
                'answer' => 'No. The bar is a demonstrator, not the project. It is used to test the material and processes quickly. The goal is to characterise a resource, build a value chain and open up several food applications.',
            ],
            [
                'question' => 'Are press cakes already eaten by people?',
                'answer' => 'Some walnut or almond press cakes are already used in artisan or culinary preparations. ReNUTS is focused on documenting composition, safety, stability and behaviour so that reproducible food uses can be considered at a larger scale.',
            ],
            [
                'question' => 'Why is this type of valorisation still limited?',
                'answer' => 'Because an interesting material is not enough. Collection, traceability, analysis, processing, stability, industrial processes and market outlets all have to be organised. ReNUTS is working to connect these steps.',
            ],
        ],
    ],
    'final' => [
        'title' => 'The material already exists. Let’s build the evidence and the value chain.',
        'cta' => 'Let’s talk',
    ],
    'footer' => [
        'legal' => 'ReNUTS project — Food R&D',
        'rights' => 'All rights reserved.',
    ],
    'hero_process' => [
        'nut' => 'NUTS',
        'pressing' => 'PRESSING',
        'powder' => 'PRESS CAKE',
        'products' => 'APPLICATIONS',
        'resource' => 'AN EXISTING RESOURCE',
        'value' => 'NEW VALUE',
    ],
];
